# Generated by Django 3.0.5 on 2020-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0004_auto_20200430_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return',
            name='end_rent',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='book_return',
            name='start_rent',
            field=models.DateField(auto_now_add=True),
        ),
    ]
