# Generated by Django 3.0.5 on 2020-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0005_auto_20200430_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_date',
        ),
    ]
