# Generated by Django 3.0.5 on 2020-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0006_remove_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(default=None),
        ),
    ]
