# Generated by Django 3.0.5 on 2020-04-30 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0009_auto_20200430_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
