# Generated by Django 3.0.5 on 2020-04-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0010_auto_20200430_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return',
            name='end_rent',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
