# Generated by Django 3.0.5 on 2020-05-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0011_auto_20200430_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_return',
        ),
    ]
