# Generated by Django 3.0.5 on 2020-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0012_delete_book_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
