# Generated by Django 3.0.5 on 2020-05-15 20:21

from django.db import migrations, models
import libra.models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0013_book_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(default=None, upload_to=libra.models.get_file_path),
        ),
    ]
