# Generated by Django 3.0.5 on 2020-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0015_auto_20200517_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
