# Generated by Django 3.0.5 on 2020-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0016_auto_20200517_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
